---
apiVersion: v1
kind: Service
metadata:
  name: inf-service
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
spec:
  selector:
    app: inf
  ports:
    - name: default
      port: 8086
      targetPort: 8086
      protocol: TCP
    - name: admin
      port: 8088
      targetPort: 8088
      protocol: TCP
  type: ClusterIP

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: influxdb-pvc
spec:
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inf-deployment
  labels:
    app: inf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inf
  template:
    metadata:
      labels:
        app: inf
    spec:
      containers:
        - name: inf
          image: ft-services-influxdb
          imagePullPolicy: Never
          ports:
            - name: default
              containerPort: 8086
              protocol: TCP
            - name: admin
              containerPort: 8088
              protocol: TCP
          volumeMounts:
            - name: influxdb-database-volume
              mountPath: /var/lib/influxdb
      volumes:
        - name: influxdb-database-volume
          persistentVolumeClaim:
            claimName: influxdb-pvc
