---
apiVersion: v1
kind: Service
metadata:
  name: pma-service
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
spec:
  selector:
    app: pma
  ports:
    - name: http
      port: 5000
      targetPort: 5000
      protocol: TCP
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pma-deployment
  labels:
    app: pma
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pma
  template:
    metadata:
      labels:
        app: pma
    spec:
      containers:
        - name: pma
          image: ft-services-phpmyadmin
          imagePullPolicy: Never
          ports:
            - name: http
              containerPort: 5000