---
apiVersion: v1
kind: Service
metadata:
  name: wp-service
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
spec:
  selector:
    app: wp
  ports:
    - name: http
      port: 5050
      targetPort: 5050
      protocol: TCP
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wp-deployment
  labels:
    app: wp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wp
  template:
    metadata:
      labels:
        app: wp
    spec:
      containers:
        - name: wp
          image: ft-services-wordpress
          env:
            - name: MINIKUBE_IP
              valueFrom:
                secretKeyRef:
                  name: minikube-ip
                  key: ip
          imagePullPolicy: Never
          ports:
            - name: http
              containerPort: 5050